### ISSUE TITLE
系统设置中的基础配置logo文件建议分开两个图片设置

### ISSUE THREAD

**Issue by xueqidove** [halo-sigs/theme-earth#1]
系统设置中设置内容参见如下
![image](https://user-images.githubusercontent.com/60059766/195819244-88443515-7f73-4b3c-ba5d-c8961b897b10.png)

用户端效果图如下
![image](https://user-images.githubusercontent.com/60059766/195818168-c95a689a-f245-483d-8281-68ad5d9fc7d9.png)

建议将用户端的效果图的两个logo分开设置，两个尺寸不大一样

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/theme-earth/commit/15a3b2b499372b656c066451ff53a175ee22791c 中支持。

/close
