### ISSUE TITLE
期望支持点击文章摘要及封面图片跳转至文章详情

### ISSUE THREAD

**Issue by intoyang** [halo-sigs/theme-earth#11]
目前支持点击文章标题进行跳转。期望点击摘要/封面图片时也能跳转至相应页面。
/kind improvement

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/theme-earth/commit/2702227d10c00c92b84ccbd5ba2c7537ded0e418 中支持了点击封面图片跳转详情，但是点击摘要的文字也可以跳转似乎需要再考虑下。
