### ISSUE TITLE
文章取消发布后仍被记入了分类和标签的统计

### ISSUE THREAD

**Issue by intoyang** [halo-sigs/theme-earth#14]
### 问题描述
文章取消发布后仍被记入了分类和标签的统计。导致分类和标签的总数与当前显示文章数量不符。
如图，仅有一篇文章公开可见。但分类数和标签数都大于 1 。
![iShot_2022-11-08_19 53 34](https://user-images.githubusercontent.com/73098982/200558627-fa7007ea-f81c-427d-9729-9433d15e9166.png)
### 期望
站在浏览者角度，文章显示数量和统计维度的总和应该一致。
也即，分类和标签的归档应以公开可见的文章为限，无需统计全部文章。
### 附加信息
/kind bug

**Comment by guqing** [comment]
https://github.com/halo-sigs/theme-earth/blob/afde519538f25479a114fc71a5a15318aa57de0e/templates/modules/category-tree.html#L11
这里取值应该使用 category.postCount 或者 category.status.visiblePostCount，tag 亦如是

**Comment by ruibaby** [comment]
> visiblePostCount

Got it!
