### ISSUE TITLE
文章列表分页页码显示问题

### ISSUE THREAD

**Issue by wan92hen** [halo-sigs/theme-earth#3]
分页文章列表的页码显示，目前为 `当前页码/总文章数` 格式，应当为 `当前页码/总页数`。

**Comment by ruibaby** [comment]
这个建议由后端提供 `totalPage` 的字段。

/cc @halo-sigs/halo

**Comment by ruibaby** [comment]
等待 https://github.com/halo-dev/halo/pull/2669 合并。

**Comment by ruibaby** [comment]
已在 https://github.com/halo-sigs/theme-earth/commit/98a95757c3ef845146112d828483306f91794d9e 中修复。
