### ISSUE TITLE
限制侧边栏显示的标签总数量

### ISSUE THREAD

**Issue by wan92hen** [halo-sigs/theme-earth#4]
当标签数量较多时，侧边栏显示出所有标签导致标签栏高度太高，页面展示效果不好。
建议增加最大显示标签数量限制，当有更多标签时通过 `...` 或 `查看更多` 选项，进入完整标签列表。

**Comment by ruibaby** [comment]
我将限制为仅显示 50 个标签，并提供 tags.html 模板。

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/theme-earth/commit/2910087c85c653e64283c4e8685da7ca6e2d9b4e 中支持。

/close
